---
title: "Project"
runtime: shiny
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(sp)
library(ggmap)
library(ggplot2)
library(readxl)
library(leaflet)
library(maps)
library(magrittr)
library(dplyr)
library(shiny)
library(scales)
library(plotly)
library(reshape2)
library(viridis)
library(gplots)
library(tidyr)
```

```{r, message=FALSE, warning=FALSE}
data1 = read_excel("data/Changes in Urban Land, Population and Density by Country.xlsx", sheet = 'Countries', skip=2)
data1 = data1[-c(1,20,21,22),-16]
data1$Country[c(4,7,13,15)] = c("North Korea", "Laos", "South Korea", "Taiwan")
country_name = data1$Country
```

```{r, message=FALSE, warning=FALSE}
data2 = read_excel("data/Urban Areas with Populations Greater Than 100,000 People.xlsx", sheet = 'Urban_Areas_by_pop', skip = 2)
data2 = data2 %>% na.omit()
data2 = data2[-1]
temp = factor(data2$Country)
levels(temp) = country_name
data2$Country = as.character(temp)
```

```{r, message=FALSE, warning=TRUE}
city_name = gsub(" urban area", "", data2$`Urban Area Name`)
city_name = gsub("'", " ", city_name)
city_name = paste(city_name, data2$Country, sep=", ")
#coord = geocode(city_name, messaging = F)
#write.csv(coord, file = "EDA_Project/data/coord.csv", row.names=FALSE)
coord = read.csv("data/coord.csv")

data2$lon = coord$lon
data2$lat = coord$lat
```

```{r, message=FALSE, warning=FALSE}
east_asia = map(regions=sov.expand(country_name), fill = T, plot = F)
east_asia$names = gsub(":.*", "", east_asia$names)
factpal = colorFactor(topo.colors(18), east_asia$names)
map = leaflet(data = east_asia) %>% 
  addProviderTiles("Esri.WorldTopoMap")%>%
   addPolygons(fillColor = ~factpal(names), stroke = F, label=east_asia$names)
```

```{r, message=FALSE, warning=FALSE}
shinyApp(
  ui = navbarPage("East Asia Urbanization", id="nav",
  tabPanel("Interactive map",
    div(class="outer",
        tags$head(
        includeCSS("styles.css")
      ),
        leafletOutput("MapPlot1",height = '100%'),
        absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE, draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto", width = 332, height = "auto",
    h2("Urbanization Explorer"),
          selectInput(inputId = "year", 
                label = "Choose a year", 
                choices = c('2000','2010')),
    
    selectInput(inputId = "taxon", 
                label = "Choose an boundary type:", 
                choices = sort(unique(data2$`Administrative boundary arrangementd`))),
          
    selectInput(inputId = "size", 
                label = "Choose a size measure", 
                choices = c('urban land in sq.km.','urban population in persons')),
    
      conditionalPanel(
         condition = "input.size == 'urban land in sq.km.'",
         sliderInput(inputId = "land",
                label = "If choose land size measure:", 
               min = 0, max = 7000, value = c(0,7000), step = 10)
      ),
    
      conditionalPanel(
         condition = "input.size == 'urban population in persons'",
         sliderInput(inputId = "time",
                label = "If choose population size measure:", 
               min = 30000, max = 42000000, value = c(30000,42000000), step = 8000)
      )
                
        ))),
    tabPanel("Data Explorer",
      fluidRow(
      column(3,
        selectInput("countries", "Countries", c("All Countries"="", sort(unique(data2$Country))), multiple=TRUE)
      ),
      column(3,
        conditionalPanel("input.countries",
          selectInput("frags", "Boundary types:", c("All Types"=""), multiple=TRUE)
        )
      ),
      
      column(3,
        conditionalPanel("input.countries",
          selectInput("cities", "Urban Areas:", c("All Urban Areas"=""), multiple=TRUE)
        )
      )
      
    ),
    hr(),
    DT::dataTableOutput("table")
             
             
             ),
  
    tabPanel("SlopePlot",
      fluidPage(
        column(3,
      selectInput(inputId = "measure", 
                label = "Choose a comparison measure:", 
                choices = c("Land area","Population","Population density"))),
      column(3,
      selectInput(inputId = "byy", 
                label = "Choose group by:", 
                choices = c("Country","Boundary type")))
      
    ),
    plotOutput("SlopePlot",height = 800)
             
             
             ),
  
  tabPanel("Plots",
           fluidPage(
             column(3,
                   selectInput(inputId = "pp",
                     label="Choose a graph:",
                     choices = c("barplot","scattorplot","dotplot","histogram")
                   ) 
                    ),
             column(8,
                    conditionalPanel("input.pp=='dotplot'",
                             selectInput(
                               inputId = "dot",
                               label = "choose a measure",
                               choices = c('Population','Land', 'Population Density')
                             )        
                      
                    ),
                    conditionalPanel("input.pp=='histogram'",
                             selectInput(
                               inputId = "hist",
                               label = "choose a variable",
                               choices = colnames(data2)[2:13]
                               # choices = append(choices,"Out of China")
                             ),
                             sliderInput(
                               inputId = "bin",label = "Choose number of bins:", min = 2, max = 100, value = 10, step = 1
                               
                             )
                      
                    )
                    
                    )
             
           ),
           plotOutput("plots",width = "100%",height = 1000)
           ),
  
  tabPanel("Heatmap",
           fluidPage(
             column(5,
                   selectInput(inputId = "heat",
                     label="Choose a variable:",
                     choices = colnames(data2)[c(3,4,7,8,11,12)]
                     
                   ) 
                    ),
             conditionalPanel("input.heat",
               column(5,
                   selectInput(inputId = "heat_measure",
                     label="Choose a heat measure for boundary types:",
                     choices = colnames(data2)[c(6,10,13)]
                   ) 
                    )
             )
             
           ),
           plotOutput("heatmap",width = "100%",height = 500)
           ),
  
  
  
  conditionalPanel("false", icon("crosshair"))
  ),
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  server = function(input, output, session) {
    
    output$MapPlot1 <- renderLeaflet({
map
    })
    
    observe({
      
      age <- input$time
      taxon <- input$taxon
      year = input$year
      size = input$size
      land = input$land
      
      
      if(year=='2000'){
        pal <- colorNumeric("viridis", data2$`Average urban population density c2000 (persons/ sq. km.)`)
        pal1 <- colorNumeric("viridis", log(data2$`Average urban population density c2000 (persons/ sq. km.)`))
        if(size=='urban land in sq.km.'){
      sites <- data2 %>% 
        filter(findInterval(data2$`Urban landa c 2000 (sq. km.)` , land) == 1 & data2$`Administrative boundary arrangementd` %in% taxon)}
        else{
          sites <- data2 %>% 
        filter(findInterval(data2$`Urban populationc c 2000 (persons)`, age) == 1 & data2$`Administrative boundary arrangementd` %in% taxon)
        }
      #print(dim(sites))
      
      pop_city = paste0( "<strong>Name: </strong>",
                    sites$`Urban Area Name`, ", ", sites$Country,
                   "<br><strong>Boundary type: </strong>",
                     sites$`Administrative boundary arrangementd`,
                     "<br><strong>Urban land 2000 (sq. km.): </strong>",
                     sites$`Urban landa c 2000 (sq. km.)`,
                     "<br><strong>Urban land 2010 (sq. km.): </strong>",
                     sites$`Urban landa c 2010 (sq. km.)`,
                     "<br><strong>Urban population 2000: </strong>",
                     sites$`Urban populationc c 2000 (persons)`,
                     "<br><strong>Urban population 2010: </strong>",
                     sites$`Urban populationc c 2010 (persons)`
                     )

      leafletProxy("MapPlot1", data=sites)  %>% 
        clearGroup(group='x') %>%
      addCircles(lng = ~lon, lat = ~lat, weight = 0.2, color = "brown",
    radius = (if(size=='urban land in sq.km.') ~`Urban landa c 2000 (sq. km.)`*200 else ~sqrt(`Urban populationc c 2000 (persons)`)*100), popup = pop_city, fillColor=~pal1(log(`Average urban population density c2000 (persons/ sq. km.)`)), stroke = T, group='x',label= (if (dim(sites)[1]==0) NULL else ~`Urban Area Name`),fillOpacity = 0.7
      )%>%
      addLegend("bottomright", pal=pal, values=data2$`Average urban population density c2000 (persons/ sq. km.)`, title="Population Density",layerId = 'a')
      }
      
      
      
      
      else{
        pal <- colorNumeric("viridis", data2$`Average urban population density c2010 (persons/ sq. km.)`)
        pal1 <- colorNumeric("viridis", log(data2$`Average urban population density c2010 (persons/ sq. km.)`))
        if(size=='urban land in sq.km.'){
      sites <- data2 %>% 
        filter(findInterval(data2$`Urban landa c 2010 (sq. km.)` , land) == 1 & data2$`Administrative boundary arrangementd` %in% taxon)}
        else{
          sites <- data2 %>% 
        filter(findInterval(data2$`Urban populationc c 2010 (persons)`, age) == 1 & data2$`Administrative boundary arrangementd` %in% taxon)
        }
      #print(dim(sites))
      
      pop_city = paste0( "<strong>Name: </strong>",
                    sites$`Urban Area Name`, ", ", sites$Country,
                   "<br><strong>Boundary type: </strong>",
                     sites$`Administrative boundary arrangementd`,
                     "<br><strong>Urban land 2000 (sq. km.): </strong>",
                     sites$`Urban landa c 2000 (sq. km.)`,
                     "<br><strong>Urban land 2010 (sq. km.): </strong>",
                     sites$`Urban landa c 2010 (sq. km.)`,
                     "<br><strong>Urban population 2000: </strong>",
                     sites$`Urban populationc c 2000 (persons)`,
                     "<br><strong>Urban population 2010: </strong>",
                     sites$`Urban populationc c 2010 (persons)`
                     )
      leafletProxy("MapPlot1", data=sites) %>% 
        clearGroup(group='x') %>%
      addCircles(lng = ~lon, lat = ~lat, weight = 0.2, color = "brown",
    radius = (if(size=='urban land in sq.km.') ~`Urban landa c 2010 (sq. km.)`*200 else ~sqrt(`Urban populationc c 2010 (persons)`)*100), popup = pop_city, fillColor = ~pal1(log(`Average urban population density c2010 (persons/ sq. km.)`)), stroke = T, group='x', label= (if (dim(sites)[1]==0) NULL else ~`Urban Area Name`), fillOpacity = 0.7
      )%>%
      addLegend("bottomright", pal=pal, values=data2$`Average urban population density c2010 (persons/ sq. km.)`, title="Population Density",layerId = 'a')
      }
      
    })

    observe({
    frags <- if (is.null(input$countries)) character(0) else {
      filter(data2, Country %in% input$countries) %>%
        `$`('Administrative boundary arrangementd') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$frags[input$frags %in% frags])
    updateSelectInput(session, "frags", choices = frags,
      selected = stillSelected)
  })
    
    observe({
    cities <- if (is.null(input$countries)) character(0) else {
      data2 %>%
        filter(Country %in% input$countries,
          is.null(input$countries) | `Administrative boundary arrangementd` %in% input$frags) %>%
        `$`('Urban Area Name') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$cities[input$cities %in% cities])
    updateSelectInput(session, "cities", choices = cities,
      selected = stillSelected)
  })

      output$table <- DT::renderDataTable({
    df <- data2 %>%
      filter(
        is.null(input$countries) | Country %in% input$countries,
        is.null(input$frags) | `Administrative boundary arrangementd` %in% input$frags,
        is.null(input$cities) | `Urban Area Name` %in% input$cities
      )
    action <- DT::dataTableAjax(session, df)

    DT::datatable(df,filter = 'top', colnames = c('Area', 'Country', 'Land(2000)', 'Land(2010)', 'Land Increase', 'Annual Rate of Land Increase', 'Population(2000)','Population(2010)', 'Population Change','Annual Rate of Population Change', 'Population Density(2000)','Population Density(2010)', 'Land Expansion per Person', 'Boundary Type', 'Longitude', 'Lantitude'), extensions = 'Responsive', options = list(ajax = list(url = action)), escape = FALSE)
  })
      
  output$SlopePlot <- renderPlot({
    
    datatouse <- select(data2,`Urban Area Name`)
    measure = input$measure
    byy = input$byy
    if(measure=="Land area"){
      datatouse$left = data2$`Urban landa c 2000 (sq. km.)`
      datatouse$right = data2$`Urban landa c 2010 (sq. km.)`
    }
    else if(measure=="Population"){
      datatouse$left = data2$`Urban populationc c 2000 (persons)`
      datatouse$right = data2$`Urban populationc c 2010 (persons)`
    }
    else{
      datatouse$left = data2$`Average urban population density c2000 (persons/ sq. km.)`
      datatouse$right = data2$`Average urban population density c2010 (persons/ sq. km.)`
    }
    if(byy=="Country"){
      datatouse$group = data2$Country
    }
    else{
      datatouse$group = data2$`Administrative boundary arrangementd`
    }
    
months<-24

p<-ggplot(datatouse) + geom_segment(aes(x=0,xend=months,y=left,yend=right,color=group),size=1)

p<-p + theme(panel.background = element_blank())
p<-p + theme(panel.grid=element_blank())
p<-p + theme(axis.ticks=element_blank())
p<-p + theme(axis.text=element_blank())
p<-p + theme(panel.border=element_blank())
p<-p + theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"))

p<-p + xlab("") + ylab(measure)
p<-p + theme(axis.title.y = element_text(vjust=-10))
p<-p + xlim((0-12),(months+12))
p<-p + ylim(0,(1*(max(datatouse$right,datatouse$left))))
name_left = paste(city_name, round(datatouse$left/1000,2), sep=" | ")
name_right = paste(round(datatouse$right/1000,2), city_name, sep=" | ")
p<-p + geom_text(label=name_right, y=datatouse$right, x=rep.int(months,869),hjust=0,size=5)
p<-p + geom_text(label=name_left, y=datatouse$left, x=rep.int( 0,869),hjust=1,size=5)

p<-p + geom_text(label="Year 2000", x=0,     y=(1.1*(max(datatouse$right,datatouse$left))),hjust= 1.2,size=0.5)
p<-p + geom_text(label="Year 2010", x=months,y=(1.1*(max(datatouse$right,datatouse$left))),hjust=-0.1,size=0.5)
p = p+ggtitle(paste("Slope plot of ", measure, " from 2000 to 2010"))+theme(plot.title = element_text(hjust = 0.5))
p    
  })
  
  output$plots = renderPlot({
    choose = input$pp
    if (choose == "barplot"){
    
    temp= select(data1, Country)
    temp$Population_Density_2000 = data1$`Average urban population density c2000 (persons/ sq. km.)`
    temp$Population_Density_2010 = data1$`Average urban population density c2010 (persons/ sq. km.)`
    temp = melt(temp,id="Country")
colnames(temp)[2:3]=c("year","Population Density")
temp$Country=factor(temp$Country,levels=temp$Country[order(-temp$`Population Density`)])
gg = ggplot(data=temp,aes(x=Country,y=`Population Density`,fill=year))+
  geom_bar(stat = "identity",position = "dodge")+
 theme(axis.text.x = element_text(angle = 20, hjust = 1))+
  ggtitle("URBAN POPULATION DENSITY BY COUNTRY 2000-2010")+theme(plot.title = element_text(hjust = 0.5))
gg}
    
    else if(choose=="scattorplot"){
      gg = ggplot(data=data2,aes(x=`Average annual rate of increase in urban land 2000 - 2010 (%)`,`Average annual rate of change of urban population (%)`))+
  geom_point(aes(color=Country))+
  geom_smooth(method = "lm")+
  scale_color_discrete()+
  ggtitle("Scattor plot of annual rate of urban land increase VS annual rate of urban population increase")+theme(plot.title = element_text(hjust = 0))+
  geom_abline(slope = 1, intercept = 0)
      gg
    }
    else if(choose=="dotplot"){
      cc = input$dot
      datatest = data2
      if (cc == 'Population'){
        
        datatest$population_increase = data2$`Change in urban population 2000 - 2010 (persons)`/data2$`Urban populationc c 2000 (persons)`

      datatest$popfactor<- findInterval(datatest$`Urban populationc c 2010 (persons)`, c(500000,1000000,5000000))
      datatest$popfactor <- plyr::mapvalues(datatest$popfactor, from = c(0,1,2,3), to = c('a', 'b', 'c','d'))
      gg = ggplot(datatest, aes(x = population_increase,fill = popfactor)) + geom_dotplot(method="histodot",binwidth = 0.05, colour=NA) +           ylim(0, 100) + 
      scale_fill_brewer(labels = c("500K", "500k - 1.0M","1.0M - 5.0M",">5.0M"))
      gg}
    else if (cc == 'Land'){
      datatest$land_increase=data2$`Increase in urban land 2000 - 2010 (sq. km.)`/data2$`Urban landa c 2000 (sq. km.)`

      datatest$landfactor<- findInterval(datatest$`Urban landa c 2000 (sq. km.)`, c(50,100,200,400,1000))
      datatest$landfactor <- plyr::mapvalues(datatest$landfactor, from = c(0,1,2,3,4,5), to = c('a', 'b', 'c','d','f','g'))
      gg = ggplot(datatest, aes(x = land_increase,fill = landfactor)) + geom_dotplot(method="histodot",binwidth = 0.05, colour=NA) +           ylim(0, 100) + 
        scale_fill_brewer(labels = c("50sq", "50sq - 100sq","100sq - 200sq","200sq - 400sq", "400sq - 1000sq",">1000sq"))
    gg}
    else {
      datatest$density_increase = (data2$`Average urban population density c2010 (persons/ sq. km.)` - data2$`Average urban population density c2000 (persons/ sq. km.)`)/data2$`Average urban population density c2000 (persons/ sq. km.)`

      datatest$densityfactor<- findInterval(datatest$`Average urban population density c2010 (persons/ sq. km.)`, c(5000,10000,15000))
      datatest$densityfactor <- plyr::mapvalues(datatest$densityfactor, from = c(0,1,2,3), to = c('e', 'f', 'g','h'))
      gg = ggplot(datatest, aes(x = density_increase,fill = densityfactor)) + geom_dotplot(method="histodot",dotsize = 0.5, colour=NA) +    ylim(0, 100) + 
      scale_fill_brewer(labels = c("5K", "5k - 10K","10K - 15",">15K"))
      gg}

      
    }
    else{
      his = input$hist
      bis = input$bin
      if(his == 'Country'){
  #       ggplot(data2,aes(data2[his]))+
  # geom_histogram(fill="skyblue", color="white", bins=bis, stat = "count")+
  # ggtitle(paste("Histogram of",his))
        
        ggplot(data2,aes(Country))+
  geom_histogram(fill="skyblue", color="white", stat = "count")+
  ggtitle("Histogram of number of urban areas in each country")+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
      }
      else if (his == "Out of China"){
        no_china=data2[which(data2$Country!="China"),]
  ggplot(no_china,aes(Country))+
    geom_histogram(fill="skyblue", color="white", stat = "count")+
    ggtitle("Histogram of number of urban areas without China")+
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
      }
      else {
      ggplot(data2,aes(data2[his]))+
  geom_histogram(fill="skyblue", color="white", bins=bis)+
  ggtitle(paste("Histogram of",his))
      }
    }
    
  })
  
  
  output$heatmap = renderPlot({
    type = input$heat
    ways = input$heat_measure
      new_data = select(data2, Country,`Administrative boundary arrangementd`)
      new_data2=data.frame(data2[ways])
      new_data=data.frame(new_data,new_data2)
      colnames(new_data)=c("country","frag","measure")
      
        temp1 = select(data2, Country)
        temp2=data.frame(data2[type])
        temp=data.frame(temp1,temp2)
        colnames(temp)=c("country","variable")
    
    if (ways=="Annual urban land growth rate"){
      temp$measure = data2$`Average annual rate of increase in urban land 2000 - 2010 (%)`
      }
    else if(ways=="Annual population growth rate"){
      temp$measure = data2$`Average annual rate of change of urban population (%)`
    }
    else{
      temp$measure = data2$`Urban expansion per additional urban inhabitant (sq. m./ person)`}
      
      temp=temp%>%
        group_by(country)%>%
        summarise(mean=mean(variable,na.rm=T),median = median(variable,na.rm=T), sd = sd(variable,na.rm=T))
      
       a<-group_by(new_data,country,frag)
        b <- summarise(a,mean=mean(measure,na.rm=T))
        b = spread(b, frag, mean)
      
      sc = data.matrix(cbind(temp[,2:4], b[,2:4]))
      row.names(sc) = temp$country
      heatmap.2(sc, scale="column", col=viridis,margins=c(1.5,10), cexRow=1,cexCol=1, main=paste("Heatmap for",type),trace="none",srtCol=0,Rowv = FALSE,Colv=FALSE)
      

    
    
  })
    
  },
  options = list(height = 600)
)
```

```{r, message=FALSE, warning=FALSE}
temp= select(data1, Country)
    temp$Population_Density_2000 = data1$`Average urban population density c2000 (persons/ sq. km.)`
    temp$Population_Density_2010 = data1$`Average urban population density c2010 (persons/ sq. km.)`
    temp = melt(temp,id="Country")
colnames(temp)[2:3]=c("year","Population Density")
temp$Country=factor(temp$Country,levels=temp$Country[order(-temp$`Population Density`)])
gg = ggplot(data=temp,aes(x=Country,y=`Population Density`,fill=year))+
  geom_bar(stat = "identity",position = "dodge")+
 theme(axis.text.x = element_text(angle = 25, hjust = 1, size=15))+
  ggtitle("URBAN POPULATION DENSITY BY COUNTRY 2000-2010 (persons/ sq.km.)")+theme(plot.title = element_text(hjust = 0.5))
gg
```







```{r}
gg = ggplot(data=data2,aes(x=`Average annual rate of increase in urban land 2000 - 2010 (%)`,`Average annual rate of change of urban population (%)`))+
  geom_point(aes(color=Country))+
  geom_smooth(method = "lm")+
  scale_color_discrete()+
  ggtitle("Scattor plot of annual rate of urban land increase VS annual rate of urban population increase")+theme(plot.title = element_text(hjust = 0.5))+
  geom_text(aes(label=`Administrative boundary arrangementd`),hjust=0, vjust=0,size=2)
ggplotly(gg)

```
```{r}
gg = ggplot(data=data2,aes(x=`Average annual rate of increase in urban land 2000 - 2010 (%)`,`Average annual rate of change of urban population (%)`))+
  geom_point(aes(color=Country))+
  geom_smooth(method = "lm")+
  scale_color_discrete()+
  ggtitle("Scattor plot of annual rate of urban land increase VS annual rate of urban population increase")+theme(plot.title = element_text(hjust = 0))+
  geom_abline(slope = 1, intercept = 0)
ggplotly(gg)
```





